security:
    encoders:
        App\Entity\User:
          algorithm: bcrypt # pour crypter le mot de passe dans la BDD
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        in_database:
            entity:
                class: App\Entity\User
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            provider: in_database
            form_login:
                login_path: security_login
                check_path: security_login
                default_target_path: home_connected

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path: /

            logout:
                path: security_logout
                target: /



            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
     #- { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/accueilSession, roles: ROLE_USER }
